# This file was created automatically using mongodb-spec-converter.
# Please review the generated file, then remove this notice.

description: bulkWrite-errorLabels

schemaVersion: '1.3'

runOnRequirements:
  -
    minServerVersion: 4.3.1
    topologies:
      - replicaset
      - sharded
      - load-balanced

createEntities:
  -
    client:
      id: &client0 client0
      useMultipleMongoses: false
  -
    database:
      id: &database0 database0
      client: *client0
      databaseName: &database_name retryable-writes-tests
  -
    collection:
      id: &collection0 collection0
      database: *database0
      collectionName: &collection_name coll

initialData:
  -
    collectionName: *collection_name
    databaseName: *database_name
    documents:
      - { _id: 1, x: 11 }
      - { _id: 2, x: 22 }

tests:
  -
    description: 'BulkWrite succeeds with RetryableWriteError from server'
    operations:
      -
        name: failPoint
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
              failCommands: [ update ]
              errorCode: 112
              errorLabels:
                - RetryableWriteError
      -
        object: *collection0
        name: bulkWrite
        arguments:
          requests:
            -
              deleteOne:
                filter: { _id: 1 }
            -
              insertOne:
                document: { _id: 3, x: 33 }
            -
              updateOne:
                filter: { _id: 2 }
                update: { $inc: { x: 1 } }
          ordered: true
        expectResult:
          deletedCount: 1
          insertedCount: 1
          insertedIds: { $$unsetOrMatches: { '1': 3 } }
          matchedCount: 1
          modifiedCount: 1
          upsertedCount: 0
          upsertedIds: {  }
    outcome:
      -
        collectionName: *collection_name
        databaseName: *database_name
        documents:
          - { _id: 2, x: 23 }
          - { _id: 3, x: 33 }
  -
    description: 'BulkWrite fails if server does not return RetryableWriteError'
    operations:
      -
        name: failPoint
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
              failCommands: [ update ]
              errorCode: 11600
              errorLabels: []
      -
        object: *collection0
        name: bulkWrite
        arguments:
          requests:
            -
              deleteOne:
                filter: { _id: 1 }
            -
              insertOne:
                document: { _id: 3, x: 33 }
            -
              updateOne:
                filter: { _id: 2 }
                update: { $inc: { x: 1 } }
          ordered: true
        expectError:
          isError: true
          errorLabelsOmit:
            - RetryableWriteError
    outcome:
      -
        collectionName: *collection_name
        databaseName: *database_name
        documents:
          - { _id: 2, x: 22 }
          - { _id: 3, x: 33 }
  -
    description: 'BulkWrite succeeds after PrimarySteppedDown'
    operations:
      -
        name: failPoint
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
              failCommands: [ update ]
              errorCode: 189
              errorLabels:
                - RetryableWriteError
      -
        object: *collection0
        name: bulkWrite
        arguments:
          requests:
            -
              deleteOne:
                filter: { _id: 1 }
            -
              insertOne:
                document: { _id: 3, x: 33 }
            -
              updateOne:
                filter: { _id: 2 }
                update: { $inc: { x: 1 } }
          ordered: true
        expectResult:
          deletedCount: 1
          insertedCount: 1
          insertedIds: { $$unsetOrMatches: { '1': 3 } }
          matchedCount: 1
          modifiedCount: 1
          upsertedCount: 0
          upsertedIds: {  }
    outcome:
      -
        collectionName: *collection_name
        databaseName: *database_name
        documents:
          - { _id: 2, x: 23 }
          - { _id: 3, x: 33 }
  -
    description: 'BulkWrite succeeds after WriteConcernError ShutdownInProgress'
    operations:
      -
        name: failPoint
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 1 }
            data:
              failCommands: [ insert ]
              errorLabels:
                - RetryableWriteError
              writeConcernError:
                code: 91
                errmsg: 'Replication is being shut down'
      -
        object: *collection0
        name: bulkWrite
        arguments:
          requests:
            -
              deleteOne:
                filter: { _id: 1 }
            -
              insertOne:
                document: { _id: 3, x: 33 }
            -
              updateOne:
                filter: { _id: 2 }
                update: { $inc: { x: 1 } }
          ordered: true
        expectResult:
          deletedCount: 1
          insertedCount: 1
          insertedIds: { $$unsetOrMatches: { '1': 3 } }
          matchedCount: 1
          modifiedCount: 1
          upsertedCount: 0
          upsertedIds: {  }
    outcome:
      -
        collectionName: *collection_name
        databaseName: *database_name
        documents:
          - { _id: 2, x: 23 }
          - { _id: 3, x: 33 }
