runOn:
  - minServerVersion: "4.1.10"
database_name: &database_name "default"
collection_name: &collection_name "default"

data:
  - &doc0
    _id: 1
    ssn:
      $binary:
        base64: {{ ciphertext("123-45-6789", field="ssn")["$binary"]["base64"] }}
        subType: "00"
  - _id: 2
    ssn:
      $binary:
        base64: "AQ=="
        subType: "06"
  - _id: 3
    ssn:
      $binary:
        base64: "AQAAa2V2aW4gYWxiZXJ0c29uCg=="
        subType: "06"

json_schema: {{schema()}}
key_vault_data: [{{key()}}]

tests:
  - description: "Wrong subtype"
    clientOptions:
      auto_encrypt_opts:
        kms_providers:
          aws: {} # Credentials filled in from environment.
    operations:
      - name: find
        arguments:
          filter: { _id: 1 }
        result:
          # gets returned without decryption
          - *doc0
  - description: "Empty data"
    clientOptions:
      auto_encrypt_opts:
        kms_providers:
          aws: {} # Credentials filled in from environment.
    operations:
      - name: find
        arguments:
          filter: { _id: 2 }
        result:
          errorContains: "malformed ciphertext"
  - description: "Malformed data"
    clientOptions:
      auto_encrypt_opts:
        kms_providers:
          aws: {} # Credentials filled in from environment.
    operations:
      - name: find
        arguments:
          filter: { _id: 3 }
        result:
          # ciphertext can only validate subtype (which is correct)
          # but takes the 16 byte UUID to look up key. Fails to find.
          errorContains: "client did not provide all keys"